name: Check app_name consistency

on: [push, pull_request]

jobs:
  check-app-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run app_name check script
        run: |
          chmod +x ./scripts/check_app_name.sh
          ./scripts/check_app_name.sh
